---
- name: Install dependencies
  package:
    name: "{{ item }}"
    state: installed
  loop:
      - git
      - gcc
      - libffi-devel
      - python-virtualenv
      - libselinux-python
      - python-netaddr
      - sshpass
      - ipmitool
      - python-pip
      - python3
      - python3-virtualenv
      - python3-libselinux
      - python3-netaddr
      - python3-pip
  become: true
  failed_when: false

- name: clone badfish
  git:
    repo: "https://github.com/redhat-performance/badfish.git"
    dest: "{{ ansible_user_dir }}/badfish"

- name: set badfish venv path
  set_fact:
    badfish_venv: "{{ ansible_user_dir }}/badfish/.venv"

- name: Create badfish virtualenv
  command: python3 -m venv {{ badfish_venv }} creates={{ badfish_venv }}

- name: Install badfish requirements
  pip:
    requirements: "{{ ansible_user_dir }}/badfish/requirements.txt"
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv: "{{ badfish_venv }}"  

- block:
  - include_tasks: tasks/copykeys.yml
    vars:
      hostname: "{{ hammer_host }}"
      ssh_user: "root"

  - include_tasks: tasks/get_interpreter.yml
    vars:
      hostname: "{{ hammer_host }}"
      user: "root"
  - name: set hammer host python interpreter
    set_fact:
      hammer_python_interpreter: "{{ python_interpreter }}"
  when: lab_name in ['scale', 'alias']

