---
- name: remove infrared
  file:
      state: absent
      path: "{{ ansible_user_dir }}/infrared"

- name: clone infrared
  git:
      repo: "https://github.com/redhat-openstack/infrared"
      dest: "{{ infrared_dir }}"
      force: yes

- name: use multihypervisors patch
  shell: |
    git fetch "https://review.gerrithub.io/redhat-openstack/infrared" refs/changes/83/461583/13 && git checkout FETCH_HEAD
    git checkout -b multi-hypervisor
  args:
    chdir: "{{ infrared_dir }}"  
  ignore_errors: true
  tags:
    - multihypervisors

- name: infrared setup
  shell: |
      virtualenv .venv && source .venv/bin/activate
      pip install --upgrade pip
      pip install --upgrade setuptools
      pip install .
      rm -rf {{ ansible_user_dir }}/.infrared
  args:
    chdir: "{{ infrared_dir }}"
  changed_when: false

- name: add infrared plugins
  shell: source .venv/bin/activate && infrared plugin add all
  args:
    chdir: "{{ infrared_dir }}"
  register: plugin_add
  until: plugin_add.rc == 0
  retries: 10
  delay: 2
  ignore_errors: true

- name: Create infrared workspace
  shell: |
    source .venv/bin/activate
    infrared workspace create {{ workspace_name }}
    infrared workspace checkout {{ workspace_name }}
  args:
    chdir: "{{ infrared_dir }}"
  vars:
      workspace_name: "{{ 'workspace_' + ansible_date_time.date + '_' + ansible_date_time.time|string|replace(':','-') }}"
